### ISSUE TITLE
Create a module for wp cli so it is possible to generate a launchpad project from wp cli

### ISSUE THREAD

**Issue by CrochetFeve0251** [CrochetFeve0251/psr2-plugin#14]

**Comment by nicomollet** [comment]
Where would that WP CLI module be located?
I don't see how we can avoid the first command:
`composer create-project wp-launchpad/launchpad my-plugin`

Then inside `my-plugin` we could have a WP CLI custom command, yes. 
Is it what we was thinking of?

**Comment by CrochetFeve0251** [comment]
@nicomollet the idea is to create [a wp-cli module](https://make.wordpress.org/cli/handbook/guides/sharing-wp-cli-packages/) so then we can chain both commands necessary to initialize a new project:
- `composer `composer create-project wp-launchpad/launchpad my-plugin`
- `bin/generate initialize`

Yes on the first usage like the cli command for Laravel or Symfony, it is more setup. However, for a person using it more regularly, it can be useful and might allow us to add more commands in the future.

**Comment by Khadreal** [comment]
First, we need to create a separate repo for this, while I'm not too much familiar on how we can submit this to wp to bundle as part of the built-in commands for wp cli.
After building we would go ahead and submit the package on Packagist pending when it'll be available as in-built for WP-CLI.

@CrochetFeve0251 could you please create a repo for this ?
